### ISSUE TITLE
Certain unicode characters (such as ñ) should not be converted.

### ISSUE THREAD

**Issue by f-prime** [wmww/destylize#12]
Certain unicode characters should not be converted because there is no real ascii equivalent. For example "ñ" gets converted to "N" by destylize. This is a bug because "ñ" and "n" are different characters with different pronunciations.

**Comment by wmww** [comment]
I mean... many of the characters Destylize intends to convert are different characters with different pronunciations, or at least meanings. If ñ is in the database, then at least one of the text converters I pulled data from is converting N to it, and so it's not entirely unreasonable to convert it back.

That being said, ñ in particular is very common, so it might make sense to blacklist it and similar from conversion? But who decides which letters are more important and which are more likely to be bad? I don't anticipate me doing a particularly good job at that.

There are also better options, such as spellchecking both converted and unconverted to see which is more likely, or allowing the user to set their preferred language and accepting only non-ASCII characters from that, but those take more work.

I don't think I'm going to implement a blacklist for now. If someone (presumably a Spanish speaker) comes along and complains that this is actually giving them trouble, then I'll look more into it.

**Comment by f-prime** [comment]
Yeah, that makes sense. I suppose implementing some kind of language setting for language specific destylizing is the most obvious way to do this. I am not exactly qualified to build that feature either. This is probably one of the areas where this problem gets a bit tricky too. Thought it'd be worth mentioning regardless.

**Comment by ghost** [comment]
Another subclass of this problem: The British Pound Sterling symbol, £, is converted to F, and the Euro symbol, €, is converted to E.

**Comment by passcod** [comment]
Diacritics in general really should not be stripped. In a personal context, `Félix` is being stripped to `Felix`, and _that is not my name_. In a wider context, removing diacritics can change the meaning of words. As an accessibility thing, it can change the *pronunciation* of words by screen-readers. This isn't *just* a per-language thing, either, especially in multi-language settings.

Rather than omitting a global list of characters, though, how about having preferences for which classes of characters get destylised? I would still argue for diacritics replacement to be disabled by default, but that way it could be re-enabled by individuals who make that trade-off.

**Comment by wmww** [comment]
All right I've updated the [Python script that generates the character mapping](https://github.com/wmww/destylize/commit/8aefe1e06bdb076558971f0e966cb458f937f4ff) to filter diacritics which had [this effect](https://github.com/wmww/destylize/commit/6085c15796db1b4b37e1369ed2505dba314f5d7a) on the char map. It's only picking up diacritics on ASCII characters, so diacritics on other characters may still be converted if they're in the data set. If that all looks reasonable to everyone I'll push a release.

**Comment by wmww** [comment]
Btw I've added ñ and some other common diacritics (sourced from the web, so real world data) to the test page, and they all work now.

**Comment by passcod** [comment]
Looks good to me, thank you!

**Comment by wmww** [comment]
The fix has been released in 1.2, which is already out on Firefox and will be on Chrome when the review completes.
